### ISSUE TITLE
Add lastRelease in repo infos

### ISSUE THREAD

**Issue by Atinux** [unjs/ungh#10]
Example: https://ungh.unjs.io/repo/unjs/h3

**Comment by thetejasmagade** [comment]
Hey Sébastien I'm working on this enhancement..
But, on my development server it's giving me **"401 Unauthorized"**. What should I've to do for fixing that?

**Comment by pi0** [comment]
@thetejasmagade Copy `server/.env.example` to `server/.env` and add a personal token.

**Comment by thetejasmagade** [comment]
**is it right @pi0 ?**

![Screenshot 2022-11-10 221353](https://user-images.githubusercontent.com/53045273/201155752-43dec797-8c7c-4a1c-9d7b-57af9aa909eb.jpg)

**Comment by pi0** [comment]
I think we can add it as `/repo/{owner}/{name}/release` endpoint  and only include `id` and `tag` fields. Later we can also add contents of the release.

**Comment by pi0** [comment]
I think we can add simplified `release: { id, tag }` to the response. Rest can be via `/releases` endpoint

**Comment by thetejasmagade** [comment]
So, basically in this `{repo}/{owner}/{name}` endpoint we want only `release: {id, tag_name}` right?

**Comment by thetejasmagade** [comment]
Now? @pi0
![Screenshot 2022-11-10 223605](https://user-images.githubusercontent.com/53045273/201160623-cd067896-fc16-45ec-bc45-71da210f0712.jpg)

**Comment by pi0** [comment]
Perfect :) Feel free to make PR.

**Comment by thetejasmagade** [comment]
Thanxk You @pi0 💗💗💗

**Comment by pi0** [comment]
It if finally added as `/releases/latest`. Thanks for PR @thetejasmagade again and @Atinux for suggesting it!

**Comment by thetejasmagade** [comment]
Hello, @pi0 can you please give me more work for same repo?
