### ISSUE TITLE
All APIs response with 401

### ISSUE THREAD

**Issue by 1natsu172** [unjs/ungh#101]
### Environment

Node.js22 and chromium browser

### Reproduction

https://ungh.cc/repos/unjs/h3

### Describe the bug

@pi0 Hello. I understand that this project is still under development, but all APIs return 401 responses. It is possible that the token is expired.

### Logs

```sh
> [GET] "https://api.github.com/repos/unjs/h3": 401 Unauthorized
```

**Comment by pi0** [comment]
should be good now. thanks for the report 🙏🏼

**Comment by 1natsu172** [comment]
Thanks for fixing it 👍
