### ISSUE TITLE
Access files `/repos/:repo/files`

### ISSUE THREAD

**Issue by Atinux** [unjs/ungh#11]
This is really useful to create our own code examples to have a great UX without having to embed CSB or SB.

**Comment by Atinux** [comment]
How to get a specific file now? :)

**Comment by pi0** [comment]
The endpoint only lists cached files which requires API key normally: https://github.com/unjs/ungh#repoownernamefilesbranch 

The contents can be loaded from https://raw.githubusercontent.com

**Comment by Atinux** [comment]
Could be nice then to add the fileUrl to get the content from it, could be `contentUrl` ?

**Comment by pi0** [comment]
Moved to https://github.com/unjs/ungh/issues/16
