### ISSUE TITLE
Endpoint for `branches`?

### ISSUE THREAD

**Issue by thetejasmagade** [unjs/ungh#14]
Something like 
```
repo/{owner}/{name}/{branches}
```

**Comment by pi0** [comment]
Seems a good idea to add 👍🏼

**Comment by thetejasmagade** [comment]
Thank you @pi0,  I am working on it. 😇

**Comment by thetejasmagade** [comment]
Is it fine @pi0 ?

![Screenshot 2022-11-14 230336](https://user-images.githubusercontent.com/53045273/201727452-3cc7ed8d-1de5-4a86-8323-5913c0d3a38b.jpg)

**Comment by thetejasmagade** [comment]
Hello @pi0,

Should I make the PR 🙂

**Comment by pi0** [comment]
Sure @thetejasmagade
