### ISSUE TITLE
Access Repo Readme

### ISSUE THREAD

**Issue by Atinux** [unjs/ungh#3]
It would be great to have access to repositories readme (useful to show it in Nuxt modules section):

URL: `/nuxt-modules/icon/readme`

**Comment by pi0** [comment]
Contents such as README can be accessed from GitHub CDN (cached). Are you thinking of making a redirect API? 

https://raw.githubusercontent.com/nuxt-modules/icon/main/README.md

**Comment by Atinux** [comment]
Would be nice to generate the URL indeed 😊

**Comment by pi0** [comment]
Added `/repo/name/readme` it returns `{ html, markdown }`.
