### ISSUE TITLE
422 Unprocessable Entity

### ISSUE THREAD

**Issue by jellydn** [unjs/ungh#30]
### Environment

By browser :)

### Reproduction

By access https://ungh.cc/repos/avencera/rustywind/releases

### Describe the bug

Follow the document and test with https://githubs.com/avencera/rustywind/releases then got below error

```
422 Unprocessable Entity
422 Unprocessable Entity (https://api.github.com/markdown)
```

**Comment by adamdicarlo0** [comment]
I was about to post an issue about this, too.


## HTTP 422 on /repos/avencera/rustywind/releases


### Reproduction

```
❯ wget https://ungh.cc/repos/avencera/rustywind/releases                                                                    
--2022-12-21 16:14:04--  https://ungh.cc/repos/avencera/rustywind/releases
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving ungh.cc (ungh.cc)... 104.21.14.199, 172.67.160.79, 2606:4700:3033::ac43:a04f, ...
Connecting to ungh.cc (ungh.cc)|104.21.14.199|:443... connected.
HTTP request sent, awaiting response... 422 Unprocessable Entity
2022-12-21 16:14:05 ERROR 422: Unprocessable Entity.


❯ curl https://ungh.cc/repos/avencera/rustywind/releases
{"url":"/repos/avencera/rustywind/releases","statusCode":422,"statusMessage":"Unprocessable Entity","message":"422 Unprocessable Entity (https://api.github.com/markdown)"}
```

The response from GitHub seems interesting, though it might be a red herring; either way, here it is with formatting:

```json
{
  "url": "/repos/avencera/rustywind/releases",
  "statusCode": 422,
  "statusMessage": "Unprocessable Entity",
  "message": "422 Unprocessable Entity (https://api.github.com/markdown)"
}
```

### Describe the bug

The `/repos/{owner}/{name}/releases` endpoint consistently return an error for this specific GitHub repository: `avencera/rustywind` (https://github.com/avencera/rustywind).

![image](https://user-images.githubusercontent.com/33694/209027453-1ddf7e15-923a-4a88-97c6-36df58983826.png)

**Comment by pi0** [comment]
Thanks for report and sorry for checking on this late. Issue was with empty release note items failing API. it should be fixed with latest commit

**Comment by adamdicarlo0** [comment]
Thank you! 🙌🏻
