### ISSUE TITLE
Add octokit types for better DX

### ISSUE THREAD

**Issue by cpreston321** [unjs/ungh#80]
### Describe the feature

Currently the data is any coming back from the fetch endpoint with types you can know what to expect from githubs side.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Good point. But think github should not break the types and not worth the complexity to add types from another tool that gets propagation time if ever github changes something. (and it is internal)

**Comment by cpreston321** [comment]
I guess that makes since, I guess it's hard to figure out the data without looking at the response types since the version of the api is defined in the headers for using github REST API itself

**Comment by pi0** [comment]
Yes. that's why i'm thinking ungh can provide a typed client. (maybe after https://github.com/unjs/ofetch/pull/371)

let's track via https://github.com/unjs/ungh/issues/4
